using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.Tilemaps;

public class BuildingSystem : MonoBehaviour
{
    public PlayerMovement playerMovement;
    
    [Header("List of Buildings")]
    public List<BuildableItem> availableBuildings;

    [Header("Placement Settings")]
    public LayerMask unbuildableLayer;
    public float gridSize = 0.5f;

    [Header("Build Zone Overlay")]
    [Range(0f, 1f)] public float overlayAlpha = 0.3f;

    [Header("Upgrade UI")]
    public Font upgradeUIFont;

    [Header("Tilemap Reference")]
    public Tilemap groundTilemap;

    [Header("Input Actions")]
    public InputActionReference toggleBuildModeAction;
    public InputActionReference leftClickAction;
    public InputActionReference rightClickAction;
    public InputActionReference pointerPositionAction;
    public InputActionReference rotateAction;

    private bool isBuildingMode = false;
    private BuildableItem currentSelection;
    private Vector2 currentMouseScreenPos;
    private Camera mainCam;
    private bool tryInteractThisFrame = false;
    private float currentRotationAngle = 0f;

    private List<GameObject> ghostBuildings = new List<GameObject>();
    private List<BuildableItem> ghostBuildingData = new List<BuildableItem>();

    private GameObject currentPreviewObject;
    private GameObject generatedCanvas;
    private GameObject buildMenuPanel;
    private GameObject upgradePanel;
    private Upgradeable currentUpgradeTarget = null;

    // ── Build Zone Overlay ───────────────────────────────────
    private GameObject buildZoneOverlay;

    private void CreateBuildZoneOverlay()
    {
        if (buildZoneOverlay != null) Destroy(buildZoneOverlay);
        buildZoneOverlay = new GameObject("BuildZoneOverlay");

        Texture2D tex = new Texture2D(4, 4) { filterMode = FilterMode.Point };
        Color[] px = new Color[16];
        for (int i = 0; i < 16; i++) px[i] = Color.white;
        tex.SetPixels(px);
        tex.Apply();

        Vector2 cellSize = groundTilemap.cellSize;
        float ppu = 4f / cellSize.x;
        Sprite squareSprite = Sprite.Create(tex, new Rect(0, 0, 4, 4), new Vector2(0.5f, 0.5f), ppu);
        int sortOrder = groundTilemap.GetComponent<TilemapRenderer>().sortingOrder + 1;

        BoundsInt bounds = groundTilemap.cellBounds;
        foreach (Vector3Int cell in bounds.allPositionsWithin)
        {
            if (!groundTilemap.HasTile(cell)) continue;
            Vector2 worldPos = groundTilemap.GetCellCenterWorld(cell);
            if (!IsPositionBuildable(worldPos)) continue;

            GameObject sq = new GameObject("Sq");
            sq.transform.SetParent(buildZoneOverlay.transform, false);
            sq.transform.position = worldPos;

            SpriteRenderer sr = sq.AddComponent<SpriteRenderer>();
            sr.sprite = squareSprite;
            sr.color = new Color(0f, 1f, 0f, overlayAlpha);
            sr.sortingOrder = sortOrder;
        }

        buildZoneOverlay.SetActive(false);
    }

    private bool IsPositionBuildable(Vector2 position)
    {
        if (MapGenerator.Instance != null)
            if (Vector2.Distance(MapGenerator.Instance.MapCenterWorld, position)
                > MapGenerator.Instance.SafeZoneWorldRadius) return false;

        return Physics2D.OverlapCircle(position, 0.1f, unbuildableLayer) == null;
    }

    private void ShowBuildZoneOverlay()
    {
        CreateBuildZoneOverlay();
        buildZoneOverlay.SetActive(true);
    }

    private void HideBuildZoneOverlay()
    {
        if (buildZoneOverlay != null) buildZoneOverlay.SetActive(false);
    }
    // ────────────────────────────────────────────────────────

    void Start()
    {
        mainCam = Camera.main;
        GenerateCompleteUI();
    }

    private void GenerateCompleteUI()
    {
        if (FindObjectOfType<EventSystem>() == null)
        {
            GameObject eventSystem = new GameObject("EventSystem");
            eventSystem.AddComponent<EventSystem>();
            eventSystem.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();
        }

        generatedCanvas = new GameObject("AutoGenerated_BuildCanvas");
        Canvas canvas = generatedCanvas.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        generatedCanvas.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        generatedCanvas.AddComponent<GraphicRaycaster>();

        DefaultControls.Resources uiResources = new DefaultControls.Resources();
        buildMenuPanel = DefaultControls.CreatePanel(uiResources);
        buildMenuPanel.transform.SetParent(generatedCanvas.transform, false);

        RectTransform panelRect = buildMenuPanel.GetComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(0.2f, 0f);
        panelRect.anchorMax = new Vector2(0.8f, 0.2f);
        panelRect.offsetMin = Vector2.zero;
        panelRect.offsetMax = Vector2.zero;
        buildMenuPanel.GetComponent<Image>().color = new Color(0, 0, 0, 0.8f);

        HorizontalLayoutGroup layout = buildMenuPanel.AddComponent<HorizontalLayoutGroup>();
        layout.childAlignment = TextAnchor.MiddleCenter;
        layout.spacing = 20;
        layout.padding = new RectOffset(10, 10, 10, 10);
        layout.childControlWidth = false;
        layout.childControlHeight = false;

        foreach (BuildableItem item in availableBuildings)
        {
            GameObject btnObj = DefaultControls.CreateButton(uiResources);
            btnObj.transform.SetParent(buildMenuPanel.transform, false);
            btnObj.name = "Btn_" + item.displayName;

            RectTransform btnRect = btnObj.GetComponent<RectTransform>();
            btnRect.sizeDelta = new Vector2(80, 80);

            Sprite prefabSprite = item.prefab.GetComponent<SpriteRenderer>().sprite;
            btnObj.GetComponent<Image>().sprite = prefabSprite;

            Text btnText = btnObj.GetComponentInChildren<Text>();
            string costLabel = string.Join(", ", item.costs.ConvertAll(c => $"{c.amount} {c.resourceType}"));
            btnText.text = $"{item.displayName}\n({costLabel})";
            btnText.alignment = TextAnchor.LowerCenter;
            btnText.color = Color.white;
            btnText.fontStyle = FontStyle.Bold;

            Outline outline = btnObj.AddComponent<Outline>();
            outline.effectColor = Color.black;

            btnObj.GetComponent<Button>().onClick.AddListener(() => SelectBuilding(item));
        }

        buildMenuPanel.SetActive(false);
    }

    void OnEnable()
    {
        if (toggleBuildModeAction != null) { toggleBuildModeAction.action.Enable(); toggleBuildModeAction.action.performed += OnToggleBuildMode; }
        if (leftClickAction != null) { leftClickAction.action.Enable(); leftClickAction.action.performed += OnLeftClick; }
        if (rightClickAction != null) { rightClickAction.action.Enable(); rightClickAction.action.performed += OnRightClick; }
        if (pointerPositionAction != null) { pointerPositionAction.action.Enable(); }
        if (rotateAction != null) { rotateAction.action.Enable(); rotateAction.action.performed += OnRotate; }
        
    }

    void OnDisable()
    {
        if (toggleBuildModeAction != null) { toggleBuildModeAction.action.performed -= OnToggleBuildMode; toggleBuildModeAction.action.Disable(); }
        if (leftClickAction != null) { leftClickAction.action.performed -= OnLeftClick; leftClickAction.action.Disable(); }
        if (rightClickAction != null) { rightClickAction.action.performed -= OnRightClick; rightClickAction.action.Disable(); }
        if (pointerPositionAction != null) { pointerPositionAction.action.Disable(); }
        if (rotateAction != null) { rotateAction.action.performed -= OnRotate; rotateAction.action.Disable(); }
    }

    void Update()
    {
        if (pointerPositionAction != null)
            currentMouseScreenPos = pointerPositionAction.action.ReadValue<Vector2>();

        if (isBuildingMode) HandlePreview();

        if (!tryInteractThisFrame) return;
        tryInteractThisFrame = false;

        if (EventSystem.current != null && EventSystem.current.IsPointerOverGameObject()) return;

        // Always try to select a building first — upgrade works outside build mode
        if (TrySelectBuildingAtMouse()) return;

        // Only place buildings when in build mode with a selection active
        if (isBuildingMode && currentSelection != null)
            PlaceGhostStructure();
        else
            CloseUpgradePanel();
    }

    // ── Upgrade Panel ────────────────────────────────────────

    private bool TrySelectBuildingAtMouse()
    {
        Vector2 mouseWorldPos = mainCam.ScreenToWorldPoint(currentMouseScreenPos);
        Collider2D hit = Physics2D.OverlapPoint(mouseWorldPos);

        if (hit != null)
        {
            Upgradeable upgradeable = hit.GetComponent<Upgradeable>()
                                   ?? hit.GetComponentInParent<Upgradeable>();
            if (upgradeable != null)
            {
                ShowUpgradePanel(upgradeable);
                return true;
            }
        }

        CloseUpgradePanel();
        return false;
    }

    private void ShowUpgradePanel(Upgradeable upgradeable)
    {
        // Clicking the same building again closes the panel (toggle)
        if (currentUpgradeTarget == upgradeable) { CloseUpgradePanel(); return; }
        CloseUpgradePanel();
        currentUpgradeTarget = upgradeable;

        upgradePanel = new GameObject("UpgradePanel");
        upgradePanel.transform.SetParent(generatedCanvas.transform, false);

        Image bg = upgradePanel.AddComponent<Image>();
        bg.color = new Color(0.1f, 0.1f, 0.1f, 0.92f);

        RectTransform rt = upgradePanel.GetComponent<RectTransform>();
        rt.sizeDelta = new Vector2(240, 0);
        rt.pivot = new Vector2(0f, 0f);
        rt.anchorMin = rt.anchorMax = new Vector2(0f, 0f);
        PositionPanelNearBuilding(rt, upgradeable.transform.position);

        ContentSizeFitter csf = upgradePanel.AddComponent<ContentSizeFitter>();
        csf.verticalFit = ContentSizeFitter.FitMode.PreferredSize;

        VerticalLayoutGroup vl = upgradePanel.AddComponent<VerticalLayoutGroup>();
        vl.childAlignment = TextAnchor.MiddleCenter;
        vl.spacing = 6;
        vl.padding = new RectOffset(12, 12, 12, 12);
        vl.childControlWidth = true;
        vl.childControlHeight = false;
        vl.childForceExpandWidth = true;

        // ── Header ───────────────────────────────────────────
        string buildingName = upgradeable.gameObject.name.Replace("(Clone)", "").Trim();
        AddLabel(upgradePanel.transform, $"<b>{buildingName}</b>", 15, new Color(1f, 0.85f, 0.3f));
        AddLabel(upgradePanel.transform, $"Level: {upgradeable.CurrentLevelName}", 12, Color.white);

        AddSeparator(upgradePanel.transform);

        // ── Stats comparison ─────────────────────────────────
        IUpgradePreview preview = upgradeable.GetComponent<IUpgradePreview>();
        if (preview != null)
        {
            string currentStats = preview.GetStatsAtLevel(upgradeable.CurrentLevel);
            AddLabel(upgradePanel.transform, currentStats, 11, new Color(0.8f, 0.8f, 0.8f));

            if (!upgradeable.IsMaxLevel && upgradeable.canBeUpgraded)
            {
                string nextStats = preview.GetStatsAtLevel(upgradeable.CurrentLevel + 1);
                AddLabel(upgradePanel.transform, $"▲  {nextStats}", 11, new Color(0.4f, 1f, 0.4f));
            }
            AddSeparator(upgradePanel.transform);
        }

        // ── Status / cost ────────────────────────────────────
        if (!upgradeable.canBeUpgraded)
        {
            AddLabel(upgradePanel.transform, "Cannot be upgraded", 12, new Color(1f, 0.4f, 0.4f));
        }
        else if (upgradeable.IsMaxLevel)
        {
            AddLabel(upgradePanel.transform, "✦ MAX LEVEL ✦", 13, new Color(1f, 0.85f, 0.3f));
        }
        else
        {
            List<ResourceCost> costs = upgradeable.GetNextUpgradeCost();
            string costStr = string.Join("   ", costs.ConvertAll(c => $"{c.amount}× {c.resourceType}"));
            AddLabel(upgradePanel.transform, $"→ {upgradeable.NextLevelName}", 12, new Color(0.4f, 0.8f, 1f));
            AddLabel(upgradePanel.transform, $"Cost:  {costStr}", 12, Color.white);
            AddSeparator(upgradePanel.transform);

            bool canAfford = costs.TrueForAll(c => InventoryManager.Instance.HasItem(c.resourceType, c.amount));
            GameObject btnObj = CreateStyledButton(upgradePanel.transform, "⬆ UPGRADE",
                canAfford ? new Color(0.2f, 0.7f, 0.2f) : new Color(0.4f, 0.4f, 0.4f));

            if (canAfford)
                btnObj.GetComponent<Button>().onClick.AddListener(() => { TryUpgrade(upgradeable); CloseUpgradePanel(); });
            else
            {
                btnObj.GetComponent<Button>().interactable = false;
                AddLabel(upgradePanel.transform, "Not enough resources", 10, new Color(1f, 0.5f, 0.5f));
            }
        }

        CreateStyledButton(upgradePanel.transform, "✕ Close", new Color(0.35f, 0.35f, 0.35f))
            .GetComponent<Button>().onClick.AddListener(CloseUpgradePanel);
    }

    private void PositionPanelNearBuilding(RectTransform panelRT, Vector3 worldPos)
    {
        Vector2 screenPos = mainCam.WorldToScreenPoint(worldPos);
        RectTransform canvasRT = generatedCanvas.GetComponent<RectTransform>();
        RectTransformUtility.ScreenPointToLocalPointInRectangle(
            canvasRT, screenPos, null, out Vector2 localPos);

        localPos += new Vector2(20f, 20f);
        float halfW = canvasRT.sizeDelta.x * 0.5f;
        float halfH = canvasRT.sizeDelta.y * 0.5f;
        localPos.x = Mathf.Clamp(localPos.x, -halfW + 130f, halfW - 130f);
        localPos.y = Mathf.Clamp(localPos.y, -halfH + 20f, halfH - 20f);

        panelRT.anchoredPosition = localPos;
    }

    private GameObject CreateStyledButton(Transform parent, string label, Color bgColor)
    {
        DefaultControls.Resources res = new DefaultControls.Resources();
        GameObject btn = DefaultControls.CreateButton(res);
        btn.transform.SetParent(parent, false);

        Text t = btn.GetComponentInChildren<Text>();
        t.text = label;
        t.font = upgradeUIFont != null ? upgradeUIFont : Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");

        btn.GetComponent<Image>().color = bgColor;
        btn.GetComponent<RectTransform>().sizeDelta = new Vector2(200, 28);
        return btn;
    }

    private void AddSeparator(Transform parent)
    {
        GameObject sep = new GameObject("Sep");
        sep.transform.SetParent(parent, false);
        sep.AddComponent<Image>().color = new Color(1f, 1f, 1f, 0.15f);
        sep.GetComponent<RectTransform>().sizeDelta = new Vector2(200, 1);
    }

    private void AddLabel(Transform parent, string text, int fontSize = 14, Color? color = null)
    {
        GameObject obj = new GameObject("Label");
        obj.transform.SetParent(parent, false);
        Text label = obj.AddComponent<Text>();
        label.text = text;
        label.color = color ?? Color.white;
        label.alignment = TextAnchor.MiddleCenter;
        label.fontSize = fontSize;
        label.supportRichText = true;
        label.font = upgradeUIFont != null ? upgradeUIFont : Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        obj.GetComponent<RectTransform>().sizeDelta = new Vector2(200, fontSize + 8);
    }

    private void TryUpgrade(Upgradeable upgradeable)
    {
        if (!upgradeable.canBeUpgraded || upgradeable.IsMaxLevel) return;

        List<ResourceCost> costs = upgradeable.GetNextUpgradeCost();
        foreach (var cost in costs)
        {
            if (!InventoryManager.Instance.HasItem(cost.resourceType, cost.amount))
            {
                Debug.Log($"Not enough {cost.resourceType}! Need {cost.amount}.");
                return;
            }
        }

        foreach (var cost in costs)
            InventoryManager.Instance.RemoveItem(cost.resourceType, cost.amount);

        upgradeable.Upgrade();
    }

    private void CloseUpgradePanel()
    {
        if (upgradePanel != null) { Destroy(upgradePanel); upgradePanel = null; }
        currentUpgradeTarget = null;
    }

    // ── Input ────────────────────────────────────────────────

    private void OnToggleBuildMode(InputAction.CallbackContext context)
    {
        if (isBuildingMode)
        {
            ConfirmAndExitBuildMode();
            playerMovement.canAttack = true;
        }
        else
        {
            EnterBuildMode();
            playerMovement.canAttack = false;
        }
    }

    private void OnRightClick(InputAction.CallbackContext context)
    {
        if (isBuildingMode) UndoLastGhostPlacement();
    }

    private void OnLeftClick(InputAction.CallbackContext context)
    {
        tryInteractThisFrame = true;
    }

    private void OnRotate(InputAction.CallbackContext context)
    {
        if (!isBuildingMode || currentSelection == null) return;
        if (!currentSelection.canBeRotated) return;
        currentRotationAngle -= 90f;
        if (currentRotationAngle <= -360f) currentRotationAngle = 0f;
    }

    // ── Build Mode ───────────────────────────────────────────

    private void EnterBuildMode()
    {
        isBuildingMode = true;
        currentRotationAngle = 0f;
        CloseUpgradePanel();
        if (buildMenuPanel != null) buildMenuPanel.SetActive(true);
        ShowBuildZoneOverlay();
    }

    public void ConfirmAndExitBuildMode()
    {
        Dictionary<string, int> totalCosts = new Dictionary<string, int>();

        foreach (var item in ghostBuildingData)
            foreach (var cost in item.costs)
            {
                if (totalCosts.ContainsKey(cost.resourceType)) totalCosts[cost.resourceType] += cost.amount;
                else totalCosts.Add(cost.resourceType, cost.amount);
            }

        bool canAffordAll = true;
        foreach (var costEntry in totalCosts)
        {
            if (!InventoryManager.Instance.HasItem(costEntry.Key, costEntry.Value))
            {
                canAffordAll = false;
                Debug.Log($"Not enough {costEntry.Key}! Needed {costEntry.Value}.");
                break;
            }
        }

        if (ghostBuildings.Count > 0 && canAffordAll)
        {
            foreach (var costEntry in totalCosts)
                InventoryManager.Instance.RemoveItem(costEntry.Key, costEntry.Value);

            foreach (var ghost in ghostBuildings)
            {
                ghost.GetComponent<SpriteRenderer>().color = Color.white;
                if (ghost.GetComponent<AudioSource>()) ghost.GetComponent<AudioSource>().Play(); //Audio played when build
                foreach (Collider2D col in ghost.GetComponentsInChildren<Collider2D>())
                    col.enabled = true;

                AStarGrid.Instance?.SetNodeWalkable(ghost.transform.position, false);
            }
        }
        else if (ghostBuildings.Count > 0)
        {
            CancelAllGhosts();
        }

        ghostBuildings.Clear();
        ghostBuildingData.Clear();

        isBuildingMode = false;
        currentSelection = null;
        CloseUpgradePanel();
        if (buildMenuPanel != null) buildMenuPanel.SetActive(false);
        DestroyPreviewObject();
        HideBuildZoneOverlay();
    }

    public void SelectBuilding(BuildableItem item)
    {
        currentSelection = item;
        currentRotationAngle = 0f;
        DestroyPreviewObject();
        CreatePreviewObject();
    }

    // ── Preview & Placement ──────────────────────────────────

    private void CreatePreviewObject()
    {
        if (currentSelection == null) return;

        currentPreviewObject = Instantiate(currentSelection.prefab);

        IRotatableBuilding rotatable = currentPreviewObject.GetComponent<IRotatableBuilding>();
        if (rotatable != null) rotatable.ApplyRotationSprite(currentRotationAngle);

        foreach (Collider2D col in currentPreviewObject.GetComponentsInChildren<Collider2D>())
            col.enabled = false;

        foreach (SpriteRenderer sr in currentPreviewObject.GetComponentsInChildren<SpriteRenderer>())
        { sr.color = new Color(1f, 1f, 1f, 0.5f); sr.sortingOrder = 100; }
    }

    private void DestroyPreviewObject()
    {
        if (currentPreviewObject != null) { Destroy(currentPreviewObject); currentPreviewObject = null; }
    }

    private void HandlePreview()
    {
        if (currentPreviewObject == null || currentSelection == null) return;

        Vector2 gridPos = GetMouseGridPosition();
        currentPreviewObject.transform.position = gridPos;
        currentPreviewObject.transform.rotation = Quaternion.Euler(0, 0, currentRotationAngle);

        IRotatableBuilding rotatable = currentPreviewObject.GetComponent<IRotatableBuilding>();
        if (rotatable != null) rotatable.ApplyRotationSprite(currentRotationAngle);

        bool canBuild = CanBuildHere(gridPos);
        foreach (SpriteRenderer sr in currentPreviewObject.GetComponentsInChildren<SpriteRenderer>())
            sr.color = canBuild ? new Color(0, 1, 0, 0.5f) : new Color(1, 0, 0, 0.5f);
    }

    private void PlaceGhostStructure()
    {
        Vector2 buildPos = GetMouseGridPosition();
        if (!CanBuildHere(buildPos)) return;

        Quaternion spawnRotation = Quaternion.Euler(0, 0, currentRotationAngle);
        GameObject ghostObj = Instantiate(currentSelection.prefab, buildPos, spawnRotation);

        IRotatableBuilding rotatable = ghostObj.GetComponent<IRotatableBuilding>();
        if (rotatable != null) rotatable.ApplyRotationSprite(currentRotationAngle);

        SpriteRenderer ghostSprite = ghostObj.GetComponent<SpriteRenderer>();
        if (ghostSprite != null) ghostSprite.color = new Color(1f, 1f, 1f, 0.5f);

        foreach (Collider2D col in ghostObj.GetComponentsInChildren<Collider2D>())
            col.enabled = false;

        ghostBuildings.Add(ghostObj);
        ghostBuildingData.Add(currentSelection);
    }

    private void UndoLastGhostPlacement()
    {
        if (ghostBuildings.Count > 0)
        {
            int lastIndex = ghostBuildings.Count - 1;
            Destroy(ghostBuildings[lastIndex]);
            ghostBuildings.RemoveAt(lastIndex);
            ghostBuildingData.RemoveAt(lastIndex);
        }
        else ConfirmAndExitBuildMode();
    }

    private void CancelAllGhosts()
    {
        foreach (var ghost in ghostBuildings) Destroy(ghost);
        ghostBuildings.Clear();
        ghostBuildingData.Clear();
    }

    // ── Grid & Placement Validation ──────────────────────────

    private Vector2 GetMouseGridPosition()
    {
        Vector2 mouseWorldPos = mainCam.ScreenToWorldPoint(currentMouseScreenPos);

        if (groundTilemap != null)
        {
            Vector3Int cellPosition = groundTilemap.WorldToCell(mouseWorldPos);
            Vector3 cellCenterPos = groundTilemap.GetCellCenterWorld(cellPosition);

            bool isRotatedVertically = Mathf.Abs(currentRotationAngle) == 90f || Mathf.Abs(currentRotationAngle) == 270f;
            if (isRotatedVertically)
            {
                cellCenterPos.x += groundTilemap.cellSize.x / 2f;
                cellCenterPos.y += groundTilemap.cellSize.y / 2f;
            }

            return new Vector2(cellCenterPos.x, cellCenterPos.y);
        }
        else
        {
            float snappedX = Mathf.Round(mouseWorldPos.x / gridSize) * gridSize;
            float snappedY = Mathf.Round(mouseWorldPos.y / gridSize) * gridSize;
            return new Vector2(snappedX, snappedY);
        }
    }

    private bool CanBuildHere(Vector2 position)
    {
        if (MapGenerator.Instance != null)
        {
            Vector2 mapCenter = MapGenerator.Instance.MapCenterWorld;
            float safeRadius = MapGenerator.Instance.SafeZoneWorldRadius;
            if (Vector2.Distance(mapCenter, position) > safeRadius) return false;
        }

        BoxCollider2D prefabCollider = currentSelection.prefab.GetComponent<BoxCollider2D>();
        if (prefabCollider != null)
        {
            Collider2D hit = Physics2D.OverlapBox(position, prefabCollider.size * 0.9f, currentRotationAngle, unbuildableLayer);
            if (hit != null) return false;

            foreach (var ghost in ghostBuildings)
            {
                BoxCollider2D ghostCol = ghost.GetComponent<BoxCollider2D>();
                if (ghostCol != null && Vector2.Distance(ghost.transform.position, position) < 0.1f) return false;
            }
        }
        else
        {
            Collider2D hit = Physics2D.OverlapCircle(position, 0.1f, unbuildableLayer);
            if (hit != null) return false;

            foreach (var ghost in ghostBuildings)
                if (Vector2.Distance((Vector2)ghost.transform.position, position) < 0.1f) return false;
        }

        return true;
    }
}

[System.Serializable]
public class ResourceCost
{
    public string resourceType = "Wood";
    public int amount = 5;
}

[System.Serializable]
public class BuildableItem
{
    public string displayName;
    public GameObject prefab;
    public bool canBeRotated = false;
    public List<ResourceCost> costs = new List<ResourceCost>();
}
