using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.Tilemaps;

public class BuildingSystem : MonoBehaviour
{
    [Header("List of Buildings")]
    public List<BuildableItem> availableBuildings;

    [Header("Placement Settings")]
    public LayerMask unbuildableLayer;
    public float gridSize = 0.5f;

    [Header("Upgrade UI")]
    public Font upgradeUIFont;

    [Header("Tilemap Reference")]
    public Tilemap groundTilemap;

    [Header("Input Actions")]
    public InputActionReference toggleBuildModeAction;
    public InputActionReference leftClickAction;
    public InputActionReference rightClickAction;
    public InputActionReference pointerPositionAction;
    public InputActionReference rotateAction;

    private bool isBuildingMode = false;
    private BuildableItem currentSelection;
    private Vector2 currentMouseScreenPos;
    private Camera mainCam;
    private bool tryBuildThisFrame = false;
    private float currentRotationAngle = 0f;

    private List<GameObject> ghostBuildings = new List<GameObject>();
    private List<BuildableItem> ghostBuildingData = new List<BuildableItem>();

    private GameObject currentPreviewObject;
    private GameObject generatedCanvas;
    private GameObject buildMenuPanel;
    private GameObject upgradePanel;

    void Start()
    {
        mainCam = Camera.main;
        GenerateCompleteUI();
    }

    private void GenerateCompleteUI()
    {
        if (FindObjectOfType<EventSystem>() == null)
        {
            GameObject eventSystem = new GameObject("EventSystem");
            eventSystem.AddComponent<EventSystem>();
            eventSystem.AddComponent<UnityEngine.InputSystem.UI.InputSystemUIInputModule>();
        }

        generatedCanvas = new GameObject("AutoGenerated_BuildCanvas");
        Canvas canvas = generatedCanvas.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        generatedCanvas.AddComponent<CanvasScaler>().uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        generatedCanvas.AddComponent<GraphicRaycaster>();

        DefaultControls.Resources uiResources = new DefaultControls.Resources();
        buildMenuPanel = DefaultControls.CreatePanel(uiResources);
        buildMenuPanel.transform.SetParent(generatedCanvas.transform, false);

        RectTransform panelRect = buildMenuPanel.GetComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(0.2f, 0f);
        panelRect.anchorMax = new Vector2(0.8f, 0.2f);
        panelRect.offsetMin = Vector2.zero;
        panelRect.offsetMax = Vector2.zero;
        buildMenuPanel.GetComponent<Image>().color = new Color(0, 0, 0, 0.8f);

        HorizontalLayoutGroup layout = buildMenuPanel.AddComponent<HorizontalLayoutGroup>();
        layout.childAlignment = TextAnchor.MiddleCenter;
        layout.spacing = 20;
        layout.padding = new RectOffset(10, 10, 10, 10);
        layout.childControlWidth = false;
        layout.childControlHeight = false;

        foreach (BuildableItem item in availableBuildings)
        {
            GameObject btnObj = DefaultControls.CreateButton(uiResources);
            btnObj.transform.SetParent(buildMenuPanel.transform, false);
            btnObj.name = "Btn_" + item.displayName;

            RectTransform btnRect = btnObj.GetComponent<RectTransform>();
            btnRect.sizeDelta = new Vector2(80, 80);

            Sprite prefabSprite = item.prefab.GetComponent<SpriteRenderer>().sprite;
            btnObj.GetComponent<Image>().sprite = prefabSprite;

            Text btnText = btnObj.GetComponentInChildren<Text>();
            string costLabel = string.Join(", ", item.costs.ConvertAll(c => $"{c.amount} {c.resourceType}"));
            btnText.text = $"{item.displayName}\n({costLabel})";
            btnText.alignment = TextAnchor.LowerCenter;
            btnText.color = Color.white;
            btnText.fontStyle = FontStyle.Bold;

            Outline outline = btnObj.AddComponent<Outline>();
            outline.effectColor = Color.black;

            btnObj.GetComponent<Button>().onClick.AddListener(() => SelectBuilding(item));
        }

        buildMenuPanel.SetActive(false);
    }

    void OnEnable()
    {
        if (toggleBuildModeAction != null) { toggleBuildModeAction.action.Enable(); toggleBuildModeAction.action.performed += OnToggleBuildMode; }
        if (leftClickAction != null) { leftClickAction.action.Enable(); leftClickAction.action.performed += OnLeftClick; }
        if (rightClickAction != null) { rightClickAction.action.Enable(); rightClickAction.action.performed += OnRightClick; }
        if (pointerPositionAction != null) { pointerPositionAction.action.Enable(); }
        if (rotateAction != null) { rotateAction.action.Enable(); rotateAction.action.performed += OnRotate; }
    }

    void OnDisable()
    {
        if (toggleBuildModeAction != null) { toggleBuildModeAction.action.performed -= OnToggleBuildMode; toggleBuildModeAction.action.Disable(); }
        if (leftClickAction != null) { leftClickAction.action.performed -= OnLeftClick; leftClickAction.action.Disable(); }
        if (rightClickAction != null) { rightClickAction.action.performed -= OnRightClick; rightClickAction.action.Disable(); }
        if (pointerPositionAction != null) { pointerPositionAction.action.Disable(); }
        if (rotateAction != null) { rotateAction.action.performed -= OnRotate; rotateAction.action.Disable(); }
    }

    void Update()
    {
        if (!isBuildingMode) return;

        if (pointerPositionAction != null)
            currentMouseScreenPos = pointerPositionAction.action.ReadValue<Vector2>();

        HandlePreview();

        if (tryBuildThisFrame)
        {
            tryBuildThisFrame = false;
            if (EventSystem.current != null && EventSystem.current.IsPointerOverGameObject()) return;
            if (TrySelectBuildingAtMouse()) return;
            if (currentSelection != null) PlaceGhostStructure();
        }
    }

    private bool TrySelectBuildingAtMouse()
    {
        Vector2 mouseWorldPos = mainCam.ScreenToWorldPoint(currentMouseScreenPos);
        Collider2D hit = Physics2D.OverlapPoint(mouseWorldPos);

        if (hit != null)
        {
            Upgradeable upgradeable = hit.GetComponent<Upgradeable>() ?? hit.GetComponentInParent<Upgradeable>();
            if (upgradeable != null) { ShowUpgradePanel(upgradeable); return true; }
        }

        CloseUpgradePanel();
        return false;
    }

    private void ShowUpgradePanel(Upgradeable upgradeable)
    {
        CloseUpgradePanel();

        upgradePanel = new GameObject("UpgradePanel");
        upgradePanel.transform.SetParent(generatedCanvas.transform, false);

        Image bg = upgradePanel.AddComponent<Image>();
        bg.color = new Color(0, 0, 0, 0.85f);
        RectTransform rt = upgradePanel.GetComponent<RectTransform>();
        rt.anchorMin = new Vector2(0.35f, 0.2f);
        rt.anchorMax = new Vector2(0.65f, 0.45f);
        rt.offsetMin = rt.offsetMax = Vector2.zero;

        VerticalLayoutGroup vLayout = upgradePanel.AddComponent<VerticalLayoutGroup>();
        vLayout.childAlignment = TextAnchor.MiddleCenter;
        vLayout.spacing = 8;
        vLayout.padding = new RectOffset(10, 10, 10, 10);
        vLayout.childControlWidth = true;
        vLayout.childControlHeight = false;

        if (!upgradeable.canBeUpgraded || upgradeable.IsMaxLevel)
        {
            AddLabel(upgradePanel.transform, upgradeable.canBeUpgraded ? "MAX LEVEL" : "Cannot be upgraded");
        }
        else
        {
            List<ResourceCost> costs = upgradeable.GetNextUpgradeCost();
            string costStr = string.Join(", ", costs.ConvertAll(c => $"{c.amount} {c.resourceType}"));
            AddLabel(upgradePanel.transform, "Upgrade?");
            AddLabel(upgradePanel.transform, $"Cost: {costStr}");

            DefaultControls.Resources res = new DefaultControls.Resources();
            GameObject btnObj = DefaultControls.CreateButton(res);
            btnObj.transform.SetParent(upgradePanel.transform, false);
            btnObj.GetComponentInChildren<Text>().text = "Upgrade";
            btnObj.GetComponent<RectTransform>().sizeDelta = new Vector2(120, 30);
            btnObj.GetComponent<Button>().onClick.AddListener(() => { TryUpgrade(upgradeable); CloseUpgradePanel(); });
        }

        DefaultControls.Resources res2 = new DefaultControls.Resources();
        GameObject closeBtn = DefaultControls.CreateButton(res2);
        closeBtn.transform.SetParent(upgradePanel.transform, false);
        closeBtn.GetComponentInChildren<Text>().text = "Close";
        closeBtn.GetComponent<RectTransform>().sizeDelta = new Vector2(120, 30);
        closeBtn.GetComponent<Button>().onClick.AddListener(CloseUpgradePanel);
    }

    private void AddLabel(Transform parent, string text)
    {
        GameObject obj = new GameObject("Label");
        obj.transform.SetParent(parent, false);
        Text label = obj.AddComponent<Text>();
        label.text = text;
        label.color = Color.white;
        label.alignment = TextAnchor.MiddleCenter;
        label.fontSize = 14;
        label.font = upgradeUIFont != null ? upgradeUIFont : Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        obj.GetComponent<RectTransform>().sizeDelta = new Vector2(200, 25);
    }

    private void TryUpgrade(Upgradeable upgradeable)
    {
        if (!upgradeable.canBeUpgraded || upgradeable.IsMaxLevel) return;

        List<ResourceCost> costs = upgradeable.GetNextUpgradeCost();
        foreach (var cost in costs)
        {
            if (!InventoryManager.Instance.HasItem(cost.resourceType, cost.amount))
            {
                Debug.Log($"Not enough {cost.resourceType}! Need {cost.amount}.");
                return;
            }
        }

        foreach (var cost in costs)
            InventoryManager.Instance.RemoveItem(cost.resourceType, cost.amount);

        upgradeable.Upgrade();
    }

    private void CloseUpgradePanel()
    {
        if (upgradePanel != null) { Destroy(upgradePanel); upgradePanel = null; }
    }

    private void OnToggleBuildMode(InputAction.CallbackContext context)
    {
        if (isBuildingMode) ConfirmAndExitBuildMode();
        else EnterBuildMode();
    }

    private void OnRightClick(InputAction.CallbackContext context)
    {
        if (isBuildingMode) UndoLastGhostPlacement();
    }

    private void OnLeftClick(InputAction.CallbackContext context)
    {
        if (isBuildingMode && currentSelection != null) tryBuildThisFrame = true;
    }

    private void OnRotate(InputAction.CallbackContext context)
    {
        if (!isBuildingMode || currentSelection == null) return;
        if (!currentSelection.canBeRotated) return;
        currentRotationAngle -= 90f;
        if (currentRotationAngle <= -360f) currentRotationAngle = 0f;
    }

    private void EnterBuildMode()
    {
        isBuildingMode = true;
        currentRotationAngle = 0f;
        CloseUpgradePanel();
        if (buildMenuPanel != null) buildMenuPanel.SetActive(true);
    }

    public void ConfirmAndExitBuildMode()
    {
        Dictionary<string, int> totalCosts = new Dictionary<string, int>();

        foreach (var item in ghostBuildingData)
            foreach (var cost in item.costs)
            {
                if (totalCosts.ContainsKey(cost.resourceType)) totalCosts[cost.resourceType] += cost.amount;
                else totalCosts.Add(cost.resourceType, cost.amount);
            }

        bool canAffordAll = true;
        foreach (var costEntry in totalCosts)
        {
            if (!InventoryManager.Instance.HasItem(costEntry.Key, costEntry.Value))
            {
                canAffordAll = false;
                Debug.Log($"Not enough {costEntry.Key}! Needed {costEntry.Value}.");
                break;
            }
        }

        if (ghostBuildings.Count > 0 && canAffordAll)
        {
            foreach (var costEntry in totalCosts)
                InventoryManager.Instance.RemoveItem(costEntry.Key, costEntry.Value);

            foreach (var ghost in ghostBuildings)
            {
                ghost.GetComponent<SpriteRenderer>().color = Color.white;
                foreach (Collider2D col in ghost.GetComponentsInChildren<Collider2D>())
                    col.enabled = true;

                // Mark building position as unwalkable in pathfinding
                AStarGrid.Instance?.SetNodeWalkable(ghost.transform.position, false);
            }
        }
        else if (ghostBuildings.Count > 0)
        {
            CancelAllGhosts();
        }

        ghostBuildings.Clear();
        ghostBuildingData.Clear();

        isBuildingMode = false;
        currentSelection = null;
        CloseUpgradePanel();
        if (buildMenuPanel != null) buildMenuPanel.SetActive(false);
        DestroyPreviewObject();
    }

    public void SelectBuilding(BuildableItem item)
    {
        currentSelection = item;
        currentRotationAngle = 0f;
        DestroyPreviewObject();
        CreatePreviewObject();
    }

    private void CreatePreviewObject()
    {
        if (currentSelection == null) return;

        currentPreviewObject = Instantiate(currentSelection.prefab);

        IRotatableBuilding rotatable = currentPreviewObject.GetComponent<IRotatableBuilding>();
        if (rotatable != null) rotatable.ApplyRotationSprite(currentRotationAngle);

        Collider2D[] cols = currentPreviewObject.GetComponentsInChildren<Collider2D>();
        foreach (Collider2D col in cols) col.enabled = false;

        SpriteRenderer[] renderers = currentPreviewObject.GetComponentsInChildren<SpriteRenderer>();
        foreach (SpriteRenderer sr in renderers) { sr.color = new Color(1f, 1f, 1f, 0.5f); sr.sortingOrder = 100; }
    }

    private void DestroyPreviewObject()
    {
        if (currentPreviewObject != null) { Destroy(currentPreviewObject); currentPreviewObject = null; }
    }

    private void HandlePreview()
    {
        if (currentPreviewObject == null || currentSelection == null) return;

        Vector2 gridPos = GetMouseGridPosition();
        currentPreviewObject.transform.position = gridPos;
        currentPreviewObject.transform.rotation = Quaternion.Euler(0, 0, currentRotationAngle);

        IRotatableBuilding rotatable = currentPreviewObject.GetComponent<IRotatableBuilding>();
        if (rotatable != null) rotatable.ApplyRotationSprite(currentRotationAngle);

        SpriteRenderer[] renderers = currentPreviewObject.GetComponentsInChildren<SpriteRenderer>();
        bool canBuild = CanBuildHere(gridPos);
        foreach (SpriteRenderer sr in renderers)
            sr.color = canBuild ? new Color(0, 1, 0, 0.5f) : new Color(1, 0, 0, 0.5f);
    }

    private void PlaceGhostStructure()
    {
        Vector2 buildPos = GetMouseGridPosition();
        if (!CanBuildHere(buildPos)) return;

        Quaternion spawnRotation = Quaternion.Euler(0, 0, currentRotationAngle);
        GameObject ghostObj = Instantiate(currentSelection.prefab, buildPos, spawnRotation);

        IRotatableBuilding rotatable = ghostObj.GetComponent<IRotatableBuilding>();
        if (rotatable != null) rotatable.ApplyRotationSprite(currentRotationAngle);

        SpriteRenderer ghostSprite = ghostObj.GetComponent<SpriteRenderer>();
        if (ghostSprite != null) ghostSprite.color = new Color(1f, 1f, 1f, 0.5f);

        foreach (Collider2D col in ghostObj.GetComponentsInChildren<Collider2D>())
            col.enabled = false;

        ghostBuildings.Add(ghostObj);
        ghostBuildingData.Add(currentSelection);
    }

    private void UndoLastGhostPlacement()
    {
        if (ghostBuildings.Count > 0)
        {
            int lastIndex = ghostBuildings.Count - 1;
            Destroy(ghostBuildings[lastIndex]);
            ghostBuildings.RemoveAt(lastIndex);
            ghostBuildingData.RemoveAt(lastIndex);
        }
        else ConfirmAndExitBuildMode();
    }

    private void CancelAllGhosts()
    {
        foreach (var ghost in ghostBuildings) Destroy(ghost);
        ghostBuildings.Clear();
        ghostBuildingData.Clear();
    }

    private Vector2 GetMouseGridPosition()
    {
        Vector2 mouseWorldPos = mainCam.ScreenToWorldPoint(currentMouseScreenPos);

        if (groundTilemap != null)
        {
            Vector3Int cellPosition = groundTilemap.WorldToCell(mouseWorldPos);
            Vector3 cellCenterPos = groundTilemap.GetCellCenterWorld(cellPosition);

            bool isRotatedVertically = Mathf.Abs(currentRotationAngle) == 90f || Mathf.Abs(currentRotationAngle) == 270f;
            if (isRotatedVertically)
            {
                cellCenterPos.x += groundTilemap.cellSize.x / 2f;
                cellCenterPos.y += groundTilemap.cellSize.y / 2f;
            }

            return new Vector2(cellCenterPos.x, cellCenterPos.y);
        }
        else
        {
            float snappedX = Mathf.Round(mouseWorldPos.x / gridSize) * gridSize;
            float snappedY = Mathf.Round(mouseWorldPos.y / gridSize) * gridSize;
            return new Vector2(snappedX, snappedY);
        }
    }

    private bool CanBuildHere(Vector2 position)
    {
        if (MapGenerator.Instance != null)
        {
            Vector2 mapCenter = MapGenerator.Instance.MapCenterWorld;
            float safeRadius = MapGenerator.Instance.SafeZoneWorldRadius;
            if (Vector2.Distance(mapCenter, position) > safeRadius) return false;
        }

        BoxCollider2D prefabCollider = currentSelection.prefab.GetComponent<BoxCollider2D>();
        if (prefabCollider != null)
        {
            Collider2D hit = Physics2D.OverlapBox(position, prefabCollider.size * 0.9f, currentRotationAngle, unbuildableLayer);
            if (hit != null) return false;

            foreach (var ghost in ghostBuildings)
            {
                BoxCollider2D ghostCol = ghost.GetComponent<BoxCollider2D>();
                if (ghostCol != null && Vector2.Distance(ghost.transform.position, position) < 0.1f) return false;
            }
        }
        else
        {
            Collider2D hit = Physics2D.OverlapCircle(position, 0.1f, unbuildableLayer);
            if (hit != null) return false;

            foreach (var ghost in ghostBuildings)
                if (Vector2.Distance((Vector2)ghost.transform.position, position) < 0.1f) return false;
        }

        return true;
    }
}

[System.Serializable]
public class ResourceCost
{
    public string resourceType = "Wood";
    public int amount = 5;
}

[System.Serializable]
public class BuildableItem
{
    public string displayName;
    public GameObject prefab;
    public bool canBeRotated = false;
    public List<ResourceCost> costs = new List<ResourceCost>();
}
